ALTER TABLE "invites" ALTER COLUMN "invite_code" SET DEFAULT '183048';
ALTER TABLE "users" ALTER COLUMN "verification_code" SET DEFAULT '845470';
ALTER TABLE "sessions" ADD COLUMN "token" varchar(256);
ALTER TABLE "sessions" ADD COLUMN "expires_in" timestamp;
ALTER TABLE "sessions" DROP COLUMN IF EXISTS "is_valid";
ALTER TABLE "groups" ADD CONSTRAINT "groups_id_unique" UNIQUE("id");
ALTER TABLE "invites" ADD CONSTRAINT "invites_id_unique" UNIQUE("id");
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_id_unique" UNIQUE("id");
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_id_unique" UNIQUE("id");
ALTER TABLE "users" ADD CONSTRAINT "users_id_unique" UNIQUE("id");